version: '3'
services:
  frontend:
    image: nginx:alpine
    container_name: website
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/:/usr/share/nginx/html
    restart: always
    links:
      - backend

  backend:
    image: node:8-alpine
    container_name: api-server
    ports:
      - '3000:3000'
    volumes:
      - ./backend/:/usr/app
    working_dir: /usr/app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: 'qa_dashboard'
      DATABASE_USER: 'qa_user'
      DATABASE_PASS: 'pass123'
    command: "npm start"

  db:
    build: ./database-service
    container_name: api-db
    volumes:
      - ./data/:/var/lib/mysql
    restart: always
